version: "3.9"

services:
  chargemap_parser:
    networks:
      - parsers_network
    build:
      context: .
    image: parser
    environment:
      PROXYPOOL_URL: "http://proxy_pool:5010/get/?type=https"
    command: [
      "python",
      "./run.py",
      "--name",
      "chargemap"
    ]

  electromaps_parser:
    image: parser
    networks:
      - parsers_network
    command: [
      "python",
      "./run.py",
      "--name",
      "electromaps"
    ]

  redis:
    networks:
      - parsers_network
    image: redis:alpine
    command: redis-server --requirepass redis_password

  proxy_pool:
    image: jhao104/proxy_pool
    networks:
      - parsers_network
    ports:
      - "5010:5010"
    environment:
      DB_CONN: "redis://:redis_password@redis:6379/0"

networks:
    parsers_network:
