version: "3.9"

services:
  chargemap_parser:
    networks:
      - parsers
    build:
      context: .
    image: parser
    environment:
      PROXYPOOL_URL: "http://proxy_pool:5010/get/?type=https"
      IS_DEBUG: "false"
    command: [
      "python",
      "./run.py",
      "--name",
      "chargemap"
    ]

  electromaps_parser:
    image: parser
    networks:
      - parsers
    environment:
      PROXYPOOL_URL: "http://proxy_pool:5010/get/?type=https"
      IS_DEBUG: "false"
    command: [
      "python",
      "./run.py",
      "--name",
      "electromaps"
    ]

  redis:
    networks:
      - parsers
    image: redis:alpine
    command: redis-server --requirepass redis_password

  proxy_pool:
    image: jhao104/proxy_pool
    networks:
      - parsers
    environment:
      DB_CONN: "redis://:redis_password@redis:6379/0"

networks:
    parsers:
      name: parsers_network
