select = [
    "F", # Pyflakes
    "E", # Pycodestyle Error
    "W", # PycodeStyle Warning
    "B", # flake8-bugbear
    "I", # Isort
    "A", # flake8-builtins
    "N", # pep8-naming
    "T20", # flake8-print
    "ANN", # flake8-annotations
    "UP", # pyupgrade
    "YTT", # flake8-2020
    "ISC", # flake8-implicit-str-concat
    "G", # flake8-logging-format
    "PIE", # flake8-pie
    "PYI", # flake8-pyi
    "SIM", # flake8-simplify
    "PTH", # flake8-use-pathlib
    "PL", # Pylint
]

ignore = [
    "PLR2004", # Magic value used in comparison
    "G004", # Logging statement uses f-string
    "ANN101", # Missing type annotation for `self` in method
    "ANN101", # Missing type annotation for `self` in method
    "PLR0913", # Too many arguments to function call (6 > 5)

]

line-length = 120

target-version = "py311"

unfixable = []
